//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsSegip
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persona", Namespace="http://tempuri.org/")]
    public partial class Persona : object
    {
        
        private string CIField;
        
        private string NombresField;
        
        private string PrimerApellidoField;
        
        private string SegundoApellidoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CI
        {
            get
            {
                return this.CIField;
            }
            set
            {
                this.CIField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombres
        {
            get
            {
                return this.NombresField;
            }
            set
            {
                this.NombresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PrimerApellido
        {
            get
            {
                return this.PrimerApellidoField;
            }
            set
            {
                this.PrimerApellidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SegundoApellido
        {
            get
            {
                return this.SegundoApellidoField;
            }
            set
            {
                this.SegundoApellidoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsSegip.wsSegipSoap")]
    public interface wsSegipSoap
    {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ci del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerificarDatos", ReplyAction="*")]
        wsSegip.VerificarDatosResponse VerificarDatos(wsSegip.VerificarDatosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerificarDatos", ReplyAction="*")]
        System.Threading.Tasks.Task<wsSegip.VerificarDatosResponse> VerificarDatosAsync(wsSegip.VerificarDatosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ci del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerDatos", ReplyAction="*")]
        wsSegip.ObtenerDatosResponse ObtenerDatos(wsSegip.ObtenerDatosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerDatos", ReplyAction="*")]
        System.Threading.Tasks.Task<wsSegip.ObtenerDatosResponse> ObtenerDatosAsync(wsSegip.ObtenerDatosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificarDatosRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificarDatos", Namespace="http://tempuri.org/", Order=0)]
        public wsSegip.VerificarDatosRequestBody Body;
        
        public VerificarDatosRequest()
        {
        }
        
        public VerificarDatosRequest(wsSegip.VerificarDatosRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerificarDatosRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ci;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombres;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string primerApellido;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string segundoApellido;
        
        public VerificarDatosRequestBody()
        {
        }
        
        public VerificarDatosRequestBody(string ci, string nombres, string primerApellido, string segundoApellido)
        {
            this.ci = ci;
            this.nombres = nombres;
            this.primerApellido = primerApellido;
            this.segundoApellido = segundoApellido;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificarDatosResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificarDatosResponse", Namespace="http://tempuri.org/", Order=0)]
        public wsSegip.VerificarDatosResponseBody Body;
        
        public VerificarDatosResponse()
        {
        }
        
        public VerificarDatosResponse(wsSegip.VerificarDatosResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerificarDatosResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool VerificarDatosResult;
        
        public VerificarDatosResponseBody()
        {
        }
        
        public VerificarDatosResponseBody(bool VerificarDatosResult)
        {
            this.VerificarDatosResult = VerificarDatosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerDatosRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerDatos", Namespace="http://tempuri.org/", Order=0)]
        public wsSegip.ObtenerDatosRequestBody Body;
        
        public ObtenerDatosRequest()
        {
        }
        
        public ObtenerDatosRequest(wsSegip.ObtenerDatosRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerDatosRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ci;
        
        public ObtenerDatosRequestBody()
        {
        }
        
        public ObtenerDatosRequestBody(string ci)
        {
            this.ci = ci;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerDatosResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerDatosResponse", Namespace="http://tempuri.org/", Order=0)]
        public wsSegip.ObtenerDatosResponseBody Body;
        
        public ObtenerDatosResponse()
        {
        }
        
        public ObtenerDatosResponse(wsSegip.ObtenerDatosResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerDatosResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public wsSegip.Persona ObtenerDatosResult;
        
        public ObtenerDatosResponseBody()
        {
        }
        
        public ObtenerDatosResponseBody(wsSegip.Persona ObtenerDatosResult)
        {
            this.ObtenerDatosResult = ObtenerDatosResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface wsSegipSoapChannel : wsSegip.wsSegipSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class wsSegipSoapClient : System.ServiceModel.ClientBase<wsSegip.wsSegipSoap>, wsSegip.wsSegipSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public wsSegipSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(wsSegipSoapClient.GetBindingForEndpoint(endpointConfiguration), wsSegipSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsSegipSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(wsSegipSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsSegipSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(wsSegipSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsSegipSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsSegip.VerificarDatosResponse wsSegip.wsSegipSoap.VerificarDatos(wsSegip.VerificarDatosRequest request)
        {
            return base.Channel.VerificarDatos(request);
        }
        
        public bool VerificarDatos(string ci, string nombres, string primerApellido, string segundoApellido)
        {
            wsSegip.VerificarDatosRequest inValue = new wsSegip.VerificarDatosRequest();
            inValue.Body = new wsSegip.VerificarDatosRequestBody();
            inValue.Body.ci = ci;
            inValue.Body.nombres = nombres;
            inValue.Body.primerApellido = primerApellido;
            inValue.Body.segundoApellido = segundoApellido;
            wsSegip.VerificarDatosResponse retVal = ((wsSegip.wsSegipSoap)(this)).VerificarDatos(inValue);
            return retVal.Body.VerificarDatosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsSegip.VerificarDatosResponse> wsSegip.wsSegipSoap.VerificarDatosAsync(wsSegip.VerificarDatosRequest request)
        {
            return base.Channel.VerificarDatosAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsSegip.VerificarDatosResponse> VerificarDatosAsync(string ci, string nombres, string primerApellido, string segundoApellido)
        {
            wsSegip.VerificarDatosRequest inValue = new wsSegip.VerificarDatosRequest();
            inValue.Body = new wsSegip.VerificarDatosRequestBody();
            inValue.Body.ci = ci;
            inValue.Body.nombres = nombres;
            inValue.Body.primerApellido = primerApellido;
            inValue.Body.segundoApellido = segundoApellido;
            return ((wsSegip.wsSegipSoap)(this)).VerificarDatosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsSegip.ObtenerDatosResponse wsSegip.wsSegipSoap.ObtenerDatos(wsSegip.ObtenerDatosRequest request)
        {
            return base.Channel.ObtenerDatos(request);
        }
        
        public wsSegip.Persona ObtenerDatos(string ci)
        {
            wsSegip.ObtenerDatosRequest inValue = new wsSegip.ObtenerDatosRequest();
            inValue.Body = new wsSegip.ObtenerDatosRequestBody();
            inValue.Body.ci = ci;
            wsSegip.ObtenerDatosResponse retVal = ((wsSegip.wsSegipSoap)(this)).ObtenerDatos(inValue);
            return retVal.Body.ObtenerDatosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsSegip.ObtenerDatosResponse> wsSegip.wsSegipSoap.ObtenerDatosAsync(wsSegip.ObtenerDatosRequest request)
        {
            return base.Channel.ObtenerDatosAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsSegip.ObtenerDatosResponse> ObtenerDatosAsync(string ci)
        {
            wsSegip.ObtenerDatosRequest inValue = new wsSegip.ObtenerDatosRequest();
            inValue.Body = new wsSegip.ObtenerDatosRequestBody();
            inValue.Body.ci = ci;
            return ((wsSegip.wsSegipSoap)(this)).ObtenerDatosAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.wsSegipSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.wsSegipSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.wsSegipSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:51403/wsSegip.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.wsSegipSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:51403/wsSegip.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            wsSegipSoap,
            
            wsSegipSoap12,
        }
    }
}
